config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :cocktails do
    resources :doses, only: [:new, :create] # "restaurants/:restaurant_id/reviews/new"
  end
  resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_one_attached :photo
  validates :name, presence: true, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates :ingredient_id, uniqueness: { scope: :cocktail_id }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def edit
    @cocktail = Cocktail.find(params[:id])
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to @cocktail
    else
      render :new
    end
  end

  def update
    @cocktail = Cocktail.find(params[:id])
    if @cocktail.update(cocktail_params)
      redirect_to @cocktail
    else
      render :edit
    end
  end

  def destroy
    @cocktail = Cocktail.find(params[:id])
    @cocktail.destroy
    redirect_to cocktails_path
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

  def new
    @dose = Dose.new
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail.id)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @cocktail = @dose.cocktail
    @dose.destroy
    redirect_to cocktail_path(@cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id, cocktail_id: @cocktail.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/edit.html.erb
<nav class="navbar fixed-top navbar-light bg-light">
  <form class="form-inline">
    <button class="btn btn-outline-success" type="button"><%= link_to 'add a cocktail', new_cocktail_path %></button>
    <button class="btn btn-outline-success" type="button"><%= link_to 'back to cocktail', cocktail_path(@cocktail)%></button>
    <button class="btn btn-outline-success" type="button"><%= link_to 'back to list', cocktails_path%></button>
  </form>
</nav>


<h1>edit cocktail name</h1>
<%= simple_form_for(@cocktail) do |f| %>
<%= f.input :name %>
<%= f.input :photo, as: :file %>
<%= f.button :submit %>
<% end %>

app/views/cocktails/index.html.erb
<nav class="navbar fixed-top navbar-light bg-light">
  <form class="form-inline">
    <button class="btn btn-outline-success" type="button"><%= link_to 'add a cocktail', new_cocktail_path %></button>
  </form>
</nav>

<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1514933651103-005eec06c04b?ixlib=rb-1.2.1&auto=format&fit=crop&w=1567&q=80);">
  <div class="container">
    <h1>Mr & Ms Cocktail</h1>
    <p>change your life, make cocktails</p>
  </div>
</div>

<div class="row row-cols-2 row-cols-md-2">

  <% @cocktails.each do |cocktail| %>
  <div class="col-6 col-md-3">
    <div class="card">
      <% unless cocktail.photo.attachment.nil? %>
        <%= cl_image_tag cocktail.photo.key, height: 300, width: 300, crop: :fill %>
      <% end %>
      <div class="card-body">
      <h2><%= link_to cocktail.name, cocktail_path(cocktail.id) %></h2>
      <%= link_to 'edit cocktail name', edit_cocktail_path(cocktail)%> | <%= link_to 'destroy', cocktail, method: :delete  %>
      </div>
    </div>
  </div>
      <% end %>
</div>

app/views/cocktails/new.html.erb
<nav class="navbar fixed-top navbar-light bg-light">
  <form class="form-inline">
    <button class="btn btn-outline-success" type="button"><%= link_to 'add a cocktail', new_cocktail_path %></button>
    <button class="btn btn-outline-success" type="button"><%= link_to 'back to list', cocktails_path%></button>
  </form>
</nav>


<h1>create a new cocktail</h1>
<%= simple_form_for(@cocktail) do |f| %>
<%= f.input :name %>
<%= f.input :photo, as: :file %>
<%= f.button :submit, class: 'btn btn-primary' %>
<% end %>

<%= link_to 'back to list', cocktails_path, class: 'btn btn-success'%>

app/views/cocktails/show.html.erb
<nav class="navbar fixed-top navbar-light bg-light">
  <form class="form-inline">
    <button class="btn btn-outline-success" type="button"><%= link_to 'add a cocktail', new_cocktail_path %></button>
    <button class="btn btn-outline-success" type="button"><%= link_to 'edit cocktail name', edit_cocktail_path(@cocktail)%></button>
    <button class="btn btn-outline-success" type="button"><%= link_to 'edit cocktail recipe', new_cocktail_dose_path(@cocktail)%></button>
    <button class="btn btn-outline-success" type="button"><%= link_to 'back to list', cocktails_path%></button>
  </form>
</nav>

<br>
<br>
<br>
<br>
<div class="card-trip">
  <div class="card-trip-infos">
  <% unless  @cocktail.photo.attachment.nil? %>
    <%= cl_image_tag @cocktail.photo.key, height: 300, width: 300, crop: :fill %>
  <% end %>
    <ul>
      <div>
        <h2><%= @cocktail.name %></h2>
        <% @cocktail.doses.each do |dose| %>
        <li>
          <div class = "recipe">
            <%= dose.ingredient.name %> .....
            <%= dose.description %>
          </div>
        <%= link_to 'destroy', dose, method: :delete  %>
        <% end %>
        </li>
      </div>
    </ul>
  </div>
</div>

app/views/doses/new.html.erb
<h1>add doses</h1>

<%= simple_form_for [@cocktail, @dose] do |f| %>
<%= f.input :description %>
<%= f.association :ingredient %>
<%= f.button :submit %>
<% end %>

<%= link_to 'back to list', cocktails_path%>
<%= link_to 'back to cocktail', cocktail_path(@cocktail)%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>